const ErrorCodes = {
  // Authentication and Authorization
  USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',
  USER_EXISTS: 'ERR_USER_EXISTS',
  INVALID_PASSWORD: 'ERR_INVALID_PASSWORD',
  UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  FORBIDDEN: 'ERR_FORBIDDEN',
  SESSION_EXPIRED: 'ERR_SESSION_EXPIRED',

  // Validation and Input Errors
  INVALID_INPUT: 'ERR_INVALID_INPUT',
  MISSING_FIELD: 'ERR_MISSING_FIELD',
  EMAIL_FORMAT_INVALID: 'ERR_EMAIL_FORMAT_INVALID',
  PASSWORD_TOO_WEAK: 'ERR_PASSWORD_TOO_WEAK',

  // Database or Resource Errors
  USER_NOT_CREATED: 'ERR_USER_NOT_CREATED',
  POST_NOT_CREATED: 'ERR_POST_NOT_CREATED',
  RESOURCE_NOT_FOUND: 'ERR_RESOURCE_NOT_FOUND',
  DATABASE_CONNECTION_FAILED: 'ERR_DATABASE_CONNECTION_FAILED',
  RESOURCE_ALREADY_EXISTS: 'ERR_RESOURCE_ALREADY_EXISTS',
  DUPLICATE_KEY: 'ERR_DUPLICATE_KEY',

  // Server or Internal Errors
  SERVER_ERROR: 'ERR_SERVER_ERROR',
  TIMEOUT_ERROR: 'ERR_TIMEOUT_ERROR',
  INTERNAL_SERVER_ERROR: 'ERR_INTERNAL_SERVER_ERROR',

  // External API or Service Errors
  EXTERNAL_API_ERROR: 'ERR_EXTERNAL_API_ERROR',
  THIRD_PARTY_SERVICE_DOWN: 'ERR_THIRD_PARTY_SERVICE_DOWN',
};

export default ErrorCodes;
